language: generic

sudo: required

services:
  - docker 
branches:
  only:
    - master

before_install:
  - docker build -t selenium-app .

after_success:
  - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
  - docker push dbdudska113/selenium-app

before_deploy:
  - ls  
  - mkdir -p move_deploy
  - mv rankingData.csv move_deploy/rankingData.csv 

deploy:
  - provider: s3
    acess_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: csvsfiles
    region: ap-northeast-2
    skip_clean: true
    acl: private
    local_dir: move_deploy

notiofications:
  email:
    recipients:
      - dbdudska113@naver.com