language: generic

sudo: required

services:
  - docker 
branches:
  only:
    - master

before_install:
  - docker build -t youngnam1004/selenium-app .

script:
  - docker run -v $(pwd):/app -e CI=true  youngnam1004/selenium-app
  - ls
  